@startuml
'https://plantuml.com/class-diagram

hide circle
hide methods

class CAMBI {
pk codicebanca
pk codicedivisacerto
pk codicedivisaincerto
pk datacambio
}

class STRUMENTI {
pk codicetitolo
}

class PREZZI {
pk codicebanca
pk codicetitolo
pk dataprezzo
--
fk codicetitolo
}

class CAUSALI {
pk codicebanca
pk codicecausale
}

class MOVIMENTI {
pk codicebanca
pk codicemovimento
pk c_rapporto
--
fk codicebanca
fk c_rapporto
--
fk codicetitolo
--
fk codicebanca
fk codicecausale
}

class CLIENTI {
pk codicebanca
pk c_cliente
}

class RAPPORTI {
pk codicebanca
pk c_rapporto
--
fk c_cliente
}

class SALDI {
pk codicebanca
pk c_rapporto
pk dt_riferimento
pk codicetitolo
--
fk codicetitolo
--
fk codicebanca
fk c_rapporto
}

PREZZI -right-* STRUMENTI

RAPPORTI -right-* CLIENTI

SALDI -up-* STRUMENTI
SALDI -right-* RAPPORTI

MOVIMENTI --* RAPPORTI
MOVIMENTI --* STRUMENTI
MOVIMENTI -left-* CAUSALI

@enduml